### ISSUE TITLE
Kytos of_core + of_l2ls possibly broken

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kytos-napps#192]
```
root@725899a3b9f8:/# kytosd 
2017-03-22 13:22:11,784 - INFO [kytos.core.controller] (MainThread) Starting Kytos - Kytos Controller
2017-03-22 13:22:11,789 - INFO [kytos.core.tcp_server] (TCP server) Kytos listening at 0.0.0.0:6633
2017-03-22 13:22:11,790 - INFO [kytos.core.controller] (RawEvent Handler) Raw Event Handler started
2017-03-22 13:22:11,790 - INFO [kytos.corroot@725899a3b9f8:/# kytosd 
2017-03-22 13:22:11,784 - INFO [kytos.core.controller] (MainThread) Starting Kytos - Kytos Controller
2017-03-22 13:22:11,789 - INFO [kytos.core.tcp_server] (TCP server) Kytos listening at 0.0.0.0:6633
2017-03-22 13:22:11,790 - INFO [kytos.core.controller] (RawEvent Handler) Raw Event Handler started
2017-03-22 13:22:11,790 - INFO [kytos.core.controller] (MsgInEvent Handler) Message In Event Handler started
2017-03-22 13:22:11,791 - INFO [kytos.core.controller] (MsgOutEvent Handler) Message Out Event Handler started
2017-03-22 13:22:11,794 - INFO [kytos.core.controller] (AppEvent Handler) App Event Handler started
2017-03-22 13:22:11,795 - INFO [kytos.core.controller] (MainThread) Loading kytos apps...
2017-03-22 13:22:11,803 - INFO [kytos.core.controller] (MainThread) Loading NApp kytos/of_core
2017-03-22 13:22:11,811 - INFO [werkzeug] (Thread-2)  * Running on http://0.0.0.0:8181/ (Press CTRL+C to quit)
2017-03-22 13:22:11,845 - INFO [kytos.core.napps] (Thread-3) Running Thread-3 App
2017-03-22 13:22:11,847 - INFO [kytos.core.controller] (MainThread) Loading NApp kytos/of_l2ls
2017-03-22 13:22:11,850 - INFO [kytos.core.napps] (Thread-4) Running Thread-4 App
2017-03-22 13:22:55,659 - INFO [kytos.core.tcp_server] (Thread-5) New connection from 172.17.0.1:41152
2017-03-22 13:22:55,660 - INFO [kytos.core.controller] (RawEvent Handler) Handling KytosEvent:kytos/core.connection.new ...
2017-03-22 13:22:55,661 - INFO [kytos.core.tcp_server] (Thread-5) Client 172.17.0.1:41152 disconnected. Reason: None
2017-03-22 13:22:55,762 - INFO [kytos.core.tcp_server] (Thread-6) New connection from 172.17.0.1:41156
2017-03-22 13:22:55,762 - INFO [kytos.core.controller] (RawEvent Handler) Handling KytosEvent:kytos/core.connection.new ...
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kytos-1.1.0b1.dev1-py3.6.egg/kytos/core/helpers.py", line 70, in threaded_handler
    handler(*args)
  File "/var/lib/kytos/napps/kytos/of_l2ls/main.py", line 54, in handle_packet_in
    switch.update_mac_table(ethernet.source, in_port)
AttributeError: 'NoneType' object has no attribute 'update_mac_table'
e.controller] (MsgInEvent Handler) Message In Event Handler started
```

**Comment by renanrodrigo** [comment]
I just tested it in several Mininet environments and it seems to be working. @beraldoleal can you give more details about how you came to this error screen?

**Comment by diraol** [comment]
@renanrodrigo have you tried running kytos on the docker instance and the mininet on your local host, outside of the mininet?
[in order to achieve this setup you will need to modify the docker config file to expose the docker 6633 port to the host, and also set the correct ip/port on the mininet]

**Comment by renanrodrigo** [comment]
I was running everything from my system. Now did everything as you said: ran kytosd inside docker and mininet in my host. Still no error.

**Comment by beraldoleal** [comment]
Closing for now.
