### ISSUE TITLE
of_stats logs are broken

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/kytos-napps#197]
As the logging process have changed recently, of_stats logs are now broken.
```
Traceback (most recent call last):
  File "/home/renn/newt/test42/bin/kytosd", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/renn/newt/kytos/bin/kytosd", line 29, in <module>
    controller.start()
  File "/home/renn/newt/kytos/kytos/core/core.py", line 153, in start
    self.load_napps()
  File "/home/renn/newt/kytos/kytos/core/core.py", line 485, in load_napps
    self.load_napp(author, napp_name)
  File "/home/renn/newt/kytos/kytos/core/core.py", line 471, in load_napp
    napp = module.load_module().Main(controller=self)
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 251, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/renn/newt/test42/var/lib/kytos/napps/kytos/of_stats/main.py", line 7, in <module>
    from napps.kytos.of_stats.stats import Description, FlowStats, PortStats
  File "/home/renn/newt/kytos-napps/napps/kytos/of_stats/stats.py", line 17, in <module>
    log = settings.log
AttributeError: module 'napps.kytos.of_stats.settings' has no attribute 'log'
```

**Comment by renanrodrigo** [comment]
Note that changing the `log` calls to `self.log` does not solve the problem. `kytosd -f` ran fine, but at the first need for a log, it says:
```
Exception in thread of_stats:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/renn/newt/kytos/kytos/core/napps.py", line 95, in run
    self.execute()
  File "/home/renn/newt/test42/var/lib/kytos/napps/kytos/of_stats/main.py", line 35, in execute
    self._update_stats(switch)
  File "/home/renn/newt/test42/var/lib/kytos/napps/kytos/of_stats/main.py", line 44, in _update_stats
    stats.request(switch.connection)
  File "/home/renn/newt/kytos-napps/napps/kytos/of_stats/stats.py", line 358, in request
    self.log.debug('Desc request for switch %s sent.', dpid)
AttributeError: 'Description' object has no attribute 'log'
```

**Comment by cemsbr** [comment]
``log`` should be removed from settings.py and NApps should use ``self.log``.

**Comment by diraol** [comment]
I haven't looked at the source, but my guess is that the log only exists as an attribute for the 'Main' class of the NApp, not for other NApp specific accessory classes. So, the NApp developer must use the log from the Main class or expose It to the other classes.

**Comment by renanrodrigo** [comment]
Right. @cemsbr 's suggestion leads to the second output shown in this issue. Trying @diraol 's.

**Comment by beraldoleal** [comment]
@macartur take a look on this. Please.

**Comment by cemsbr** [comment]
Indeed, it is not trivial. There are some static methods that uses the log. My suggestion is to make *log* a class attribute. What do you think, @diraol ?

**Comment by diraol** [comment]
@cemsbr since we may have some static and class methods that would use the log, this may be a good approach indeed.

But I still don't know how to handle log messages from accessory classes that are on other (sub)modules from a NApp, such as the `Stats` or `PortStats`  classes on the `stats` module of `of_stats` NApp.

And I'm saying this because the log only exists, for now, on the `Main` class from the `main` module. This module imports the other ones, so they can not import the `Main` module because it would create a import loop.

One options is to let the `Main` class deal with all log messages, even from the other methods. But I'm not sure how to do it.

**Comment by cemsbr** [comment]
As we've discussed, we can either let the user pass the log to other classes/objects or create a ``log`` variable that the user can easily import.

**Comment by beraldoleal** [comment]
As we discussed lets create a "central core log". Should be nice to a NApp have:

```
from kytos.core import log
```

And the core take care of start the proper log handler.
