### ISSUE TITLE
of_stats rrdtool OperationalErrors

### ISSUE THREAD

**Issue by erickvermot** [kytos/kytos-napps#224]
Controller starts ok,
mininet starts ok,
pingall goes ok,
but when closing mininet, rrdtool raises a OperationalError:

```
Exception in thread Thread-3194:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/kytos-2017.1b2.post2-py3.6.egg/kytos/core/helpers.py", line 68, in threaded_handler
    handler(*args)
  File "//var/lib/kytos/napps/kytos/of_stats/main.py", line 53, in listener
    stats.listen(event.source.switch.dpid, msg.body)
  File "/home/user/dev/kytos/kytos_platform/kytos-napps/napps/kytos/of_stats/stats.py", line 338, in listen
    byte_count=fs.byte_count.value)
  File "/home/user/dev/kytos/kytos_platform/kytos-napps/napps/kytos/of_stats/stats.py", line 81, in update
    rrdtool.update(rrd, '{}:{}'.format(tstamp, data))
rrdtool.OperationalError: mmaping file '/mnt/USB8/home/user/dev/kytos/kytos_platform/kytos-napps/napps/kytos/of_stats/rrd/flows/00:00:00:00:00:00:00:02/4255b810802711c1b082648dcdab1fc8.rrd': Invalid argument
```

**Comment by erickvermot** [comment]
This other OperationalError happened during ping,
idk if it is related to the same problem as the other one or not.

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/kytos-2017.1b2.post2-py3.6.egg/kytos/core/helpers.py", line 68, in threaded_handler
    handler(*args)
  File "//var/lib/kytos/napps/kytos/of_stats/main.py", line 53, in listener
    stats.listen(event.source.switch.dpid, msg.body)
  File "/home/user/dev/kytos/kytos_platform/kytos-napps/napps/kytos/of_stats/stats.py", line 276, in listen
    tx_errors=ps.tx_errors.value)
  File "/home/user/dev/kytos/kytos_platform/kytos-napps/napps/kytos/of_stats/stats.py", line 81, in update
    rrdtool.update(rrd, '{}:{}'.format(tstamp, data))
rrdtool.OperationalError: '/mnt/USB8/home/user/dev/kytos/kytos_platform/kytos-napps/napps/kytos/of_stats/rrd/ports/00:00:00:00:00:00:00:01/3.rrd' is too small (should be 8325840 bytes)
```

**Comment by erickvermot** [comment]
yet another one... this one seems different.
Should I open separate issues?

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/kytos-2017.1b2.post2-py3.6.egg/kytos/core/helpers.py", line 68, in threaded_handler
    handler(*args)
  File "//var/lib/kytos/napps/kytos/of_stats/main.py", line 53, in listener
    stats.listen(event.source.switch.dpid, msg.body)
  File "/home/user/dev/kytos/kytos_platform/kytos-napps/napps/kytos/of_stats/stats.py", line 276, in listen
    tx_errors=ps.tx_errors.value)
  File "/home/user/dev/kytos/kytos_platform/kytos-napps/napps/kytos/of_stats/stats.py", line 78, in update
    rrd = self.get_or_create_rrd(index)
  File "/home/user/dev/kytos/kytos_platform/kytos-napps/napps/kytos/of_stats/stats.py", line 123, in get_or_create_rrd
    self.create_rrd(rrd, tstamp)
  File "/home/user/dev/kytos/kytos_platform/kytos-napps/napps/kytos/of_stats/stats.py", line 146, in create_rrd
    rrdtool.create(*options)
rrdtool.OperationalError
```

**Comment by erickvermot** [comment]
the rrd folder grew to more than 1.5G and filled my home partition (where the of_stats napp is located in my case). Because it was not the system partition, arch did not warn me, and I did not realize it at the time.
Deleting the rrd folder and freeing some space made the Exceptions disappear.
I'll close the issue as I believe this was the problem. If anyone notices it in some other condition, please reopen.
