### ISSUE TITLE
Unpack exceptions in of.core

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/kytos-napps#226]
`python-openflow` raises several Unpack exceptions when running kytos with the `of_core` NApp.

~~Each packet-in generates an exception.~~ Please see edit below.

Enabled NApps: `of_core` and `of_l2ls`
Mininet topology: any.

Exception:
```
Traceback (most recent call last):
  File "/home/renan/testes/asd/lib/python3.6/site-packages/pyof/foundation/base.py", line 193, in unpack
    self._value = self.enum_ref(self._value)
  File "/usr/lib/python3.6/enum.py", line 291, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.6/enum.py", line 533, in __new__
    return cls._missing_(value)
  File "/usr/lib/python3.6/enum.py", line 546, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 2 is not a valid Port

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/renan/testes/asd/lib/python3.6/site-packages/kytos-2017.1b2.post2-py3.6.egg/kytos/core/helpers.py", line 68, in threaded_handler
    handler(*args)
  File "/home/renan/testes/asd/var/lib/kytos/napps/kytos/of_core/main.py", line 126, in handle_new_openflow_message
    message.unpack(binary_data)
  File "/home/renan/testes/asd/lib/python3.6/site-packages/pyof/v0x01/asynchronous/error_msg.py", line 209, in unpack
    self.data = self._unpack_data()
  File "/home/renan/testes/asd/lib/python3.6/site-packages/pyof/v0x01/asynchronous/error_msg.py", line 223, in _unpack_data
    msg.unpack(msg_data)
  File "/home/renan/testes/asd/lib/python3.6/site-packages/pyof/v0x01/controller2switch/packet_out.py", line 101, in unpack
    attribute.unpack(buff, begin)
  File "/home/renan/testes/asd/lib/python3.6/site-packages/pyof/foundation/base.py", line 197, in unpack
    raise UnpackException(msg)
pyof.foundation.exceptions.UnpackException: 2 is not a valid Port; fmt = !H, buff = b'\x00\x00\x01X\x00\x02\x00\x08\x00\x00\x00\x08\x00\x01\xff\xff\xda\x19\x106\xbb6\x12\x88\xa3\xc9LU\x08\x06\x00\x01\x08.
```

**Comment by macartur** [comment]
I had this error,  but using `kytos/tryfirst` this error doesn't appear.

**Comment by renanrodrigo** [comment]
Lots of packet_ins are processed without any exception. Actually, switch is sending an `ErrorMsg` and `python-openflow` is not unpacking it the right way.

**Comment by erickvermot** [comment]
This is a problem with pyof.asunchronous.error_msg ErrorMsg.
of_core calls unpack with the body binary data (of_core.main line 127), but ErrorMsg treats it as if the binary contained the whole msg (error_msg.py lines 211 to 225)

**Comment by renanrodrigo** [comment]
So we must:
- Check why this error happens and
- Fix error messages unpacking in kytos/python-openflow. I'm opening an issue there.

**Comment by renanrodrigo** [comment]
Those errors are happening because we are sending two different answers with the same buffer ID. The solution is never sending the buffer ID with the Flow Mod, but only with the Packet Out.
If the swtich has buffers, it will have just one action to perform related to the buffered packet.
If the switch does not has buffers (or does not use it), it does not matter as the `data` field of the Packet In is always sent with the Packet Out.

**Comment by erickvermot** [comment]
I agree the buffer does not need to be sent with the flow_mod.
And I agree with the PR.

But in the PR it says it Fixes the issues, but I think although it fixes the problem experienced in this particular case, there are more problems discussed here that need to be fixed.

**Comment by beraldoleal** [comment]
I will accept the PR because I would like to see the things moving on. But if any problem persists, please reopen.
