### ISSUE TITLE
[kytos/of_core] Say hello is breaking sometimes

### ISSUE THREAD

**Issue by macartur** [kytos/kytos-napps#257]
Following the steps below to reproduce this error:

- Run the container kytos/tryfirst: 
  `docker run -it --privileged kytos/tryfirst`
- Run kytos: 
  `kytosd -f`
- Install the napps (kytos/of_core and kytos/of_l2ls):
  `kytos napps install kytos/of_core kytos/of_l2ls`
- Stop kytos: 
  `press ctrl+ c`
- Run mininet:  
  `mn --topo linear,2 --mac --controller=remote,ip=127.0.0.1 --switch ovsk,protocols=OpenFlow10`
- Run kytos: 
  `kytosd -f`

After that may appear the traceback below.

```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kytos-2017.1b3-py3.6.egg/kytos/core/helpers.py", line 68, in threaded_handler
    handler(*args)
  File "/var/lib/kytos/napps/kytos/of_core/main.py", line 218, in handle_core_new_connection
    self._say_hello(event.source)
  File "/var/lib/kytos/napps/kytos/of_core/main.py", line 227, in _say_hello
    hello = GenericHello(versions=self.versions, xid=xid)
AttributeError: 'Main' object has no attribute 'versions'
```

```
kytos $> Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kytos-2017.1b3-py3.6.egg/kytos/core/helpers.py", line 68, in threaded_handler
    handler(*args)
  File "/var/lib/kytos/napps/kytos/of_core/main.py", line 138, in handle_raw_in
    self._negotiate(connection, message)
  File "/var/lib/kytos/napps/kytos/of_core/main.py", line 253, in _negotiate
    version = self._get_version_from_header(message.header.version)
  File "/var/lib/kytos/napps/kytos/of_core/main.py", line 237, in _get_version_from_header
    version = min(message_version, max(self.versions))
AttributeError: 'Main' object has no attribute 'versions'
2017-06-20 15:16:55,492 - INFO [root] (of_core) Running NApp: <Main(of_core, started 140550218356480)>
```

**Comment by erickvermot** [comment]
This is a concurrency problem. It is related to the way the TCP server architecture and initialization was thought and not to the say hello method.
Say hello is beeing called before the napp is initialized, because mininet was run before kytos, and the way the TCP server is implemented right now, it is started and listens to 6633 before of_core napp is even initialized.
This will no longer be a problem once I move the TCP server out of the core and inside of_core.

As we have discussed before, kytos should only start listening to 6633 once everything is up and ready to work.

**Comment by erickvermot** [comment]
@macartur, your PR https://github.com/kytos/kytos-napps/pull/260 only moves the ``versions`` to the setting, it is necessary, but does not solves the general problem as I stated in the last comment. So I think the issue should not be closed by it.
