### ISSUE TITLE
[kytos/of_stats]  Try to access /kytos/stats/00:00:00:00:00:00:00:02/ports without rrd file.

### ISSUE THREAD

**Issue by macartur** [kytos/kytos-napps#258]
Exception
-------------
```
[2017-06-20 13:24:26,401] ERROR in app: Exception on /kytos/stats/00:00:00:00:00:00:00:02/ports [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/lib/kytos/napps/../napps/kytos/of_stats/stats_api.py", line 155, in get_ports_list
    return api.get_list()
  File "/var/lib/kytos/napps/../napps/kytos/of_stats/stats_api.py", line 159, in get_list
    return super().get_latest(lambda sw: (sw.interfaces[k]
  File "/var/lib/kytos/napps/../napps/kytos/of_stats/stats_api.py", line 42, in get_latest
    data = list(self._get_latest_stats(items))
  File "/var/lib/kytos/napps/../napps/kytos/of_stats/stats_api.py", line 166, in _get_latest_stats
    row = self._rrd.fetch_latest(index)
  File "/var/lib/kytos/napps/../napps/kytos/of_stats/stats.py", line 228, in fetch_latest
    for tstamp, row in zip(tstamps[::-1], rows[::-1]):
UnboundLocalError: local variable 'tstamps' referenced before assignment
```

Description
---------------

To solve this issue is necessary to create tests for fetch_latest with an invalid file path and fix to not appear the traceback above.

**Comment by cemsbr** [comment]
Note: it can happen between launching the controller and receiving the first stats reply.
