### ISSUE TITLE
[kytos/{of_l2ls, of_topology}] Napps are breaking when switch is None.

### ISSUE THREAD

**Issue by macartur** [kytos/kytos-napps#261]
Description
--------------

When a switch is disconnected and connected again the napps `kytos/of_l2ls` and `kytos/of_topology` are breaking.

Steps to reproduce
------------------------
Enabled napps: `kytos/of_core`, `kytos/of_l2ls`, `kytos/of_topology`
Start Kytos:  `kytosd -f`
Start mininet: `mn --topo linear,5 --mac --controller=remote,ip=172.17.0.1 --switch ovsk,protocols=OpenFlow10`
Stop mininet: press ctrl+ c
Start mininet: `mn --topo linear,5 --mac --controller=remote,ip=172.17.0.1 --switch ovsk,protocols=OpenFlow10`

Traceback
--------------
``
Exception in thread Thread-39:                      
Traceback (most recent call last):                  
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner                                  
    self.run()            
  File "/usr/lib/python3.6/threading.py", line 864, in run                                               
    self._target(*self._args, **self._kwargs)       
  File "/home/macartur/Desktop/unesp/github/kytos/kytos/core/helpers.py", line 68, in threaded_handler   
    handler(*args)        
  File "/home/macartur/Envs/kytos/var/lib/kytos/napps/kytos/of_l2ls/main.py", line 59, in handle_packet_n
    switch.update_mac_table(ethernet.source, in_port)                                                    
AttributeError: 'NoneType' object has no attribute 'update_mac_table'   
``

``                                 
Exception in thread Thread-40:                      
Traceback (most recent call last):                  
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner                                  
    self.run()            
  File "/usr/lib/python3.6/threading.py", line 864, in run                                               
    self._target(*self._args, **self._kwargs)       
  File "/home/macartur/Desktop/unesp/github/kytos/kytos/core/helpers.py", line 68, in threaded_handler   
    handler(*args)        
  File "/home/macartur/Envs/kytos/var/lib/kytos/napps/kytos/of_topology/main.py", line 52, in update_lins
    interface = switch.get_interface_by_port_no(port_no.value)                                           
AttributeError: 'NoneType' object has no attribute 'get_interface_by_port_no'   
``

**Comment by erickvermot** [comment]
@macartur, I'm not saying the problem does not exist for sure, but if I include ``mn -c`` between calls to mininet, I cannot reproduce the error.... I'll keep trying.

**Comment by erickvermot** [comment]
One possibility is that the ``Connection`` did not have the time to change states before the new connection attempt, I'll investigate more.

**Comment by erickvermot** [comment]
I made some state handling improvements to avoid this kind of problem,
you can test it with the branches:
https://github.com/erickvermot/kytos/tree/connection_state_improvement
https://github.com/erickvermot/kytos-napps/tree/connection_state_improvement

I have not made the PR because it includes @macartur 's PR https://github.com/kytos/kytos/pull/467, that was not accepted yet.
Since his PR does not include a few commits that are already in the master branch, I'll wait until it is accepted before making mine, otherwise github makes a mess...

**Comment by erickvermot** [comment]
@macartur, see if you still have this issue with these mods, otherwise please close the issue.

**Comment by macartur** [comment]
I can't reproduce this error. I will close this issue.
